version: '2'
services:
  jhipstermessageapplication-app:
    image: jhipstermessageapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstermessageapplication-mysql:3306/jhipstermessageapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipstermessageapplication-mysql:
    extends:
      file: mysql.yml
      service: jhipstermessageapplication-mysql
